### ISSUE TITLE
in Mac font Book... small problem

### ISSUE THREAD

**Issue by amelchi** [steinbergmedia/bravura#33] opened 2020-07-13 08:54 UTC
<img width="616" alt="Schermata 2020-07-13 alle 10 51 58" src="https://user-images.githubusercontent.com/1053312/87284867-2716e700-c4f7-11ea-92f4-034283705662.png">

**Comment by dspreadbury** [comment] 2020-10-26 23:25
This is probably a duplicate of #32.

**Closed by dspreadbury** 2020-10-26 23:25 UTC
